### PR TITLE
Patch catkin_replace_imported_library_targets() function to fix handling of transitive link dependencies

### PR DESCRIPTION
**Pull request by meyerj**
catkin provides a cmake function [catkin_replace_imported_library_targets()](https://github.com/ros/catkin/blob/0.7.14/cmake/catkin_libraries.cmake#L127) that gets called from [catkin_package()](https://github.com/ros/catkin/blob/0.7.14/cmake/catkin_package.cmake#L258) to resolve target names of libraries mentioned in `catkin_package(LIBRARIES ...)` or exported by dependencies through `catkin_package(DEPENDS ...)` to their full paths.

It also takes care of so called [INTERFACE_LINK_LIBRARIES](https://cmake.org/cmake/help/v3.0/prop_tgt/INTERFACE_LINK_LIBRARIES.html) of library targets, which lists other libraries (or other targets) that need to be linked, too (transitive link dependencies). CMake itself takes care of this and adds all the recursive `INTERFACE_LINK_LIBRARIES` of a target to the linker command line. But `catkin_replace_imported_library_targets()` does so in an incomplete way that breaks static builds, especially when exporting `OpenCV` as a dependency (like for example in [image_geometry/CMakeLists.txt](https://github.com/ros-perception/vision_opencv/blob/1.12.8/image_geometry/CMakeLists.txt#L8). `${OpenCV_LIBRARIES}` contains a list of imported targets and many of them have `INTERFACE_LINK_LIBRARIES` pointing to other public or private link dependencies (HAL, 3rd-party libraries compiled along with OpenCV, ...). The original implementation of `catkin_replace_imported_library_targets()` assumes that only targets of type `INTERFACE_LIBRARY` can have an `INTERFACE_LINK_LIBRARIES` property, but in fact every target can and will have link dependencies. An `INTERFACE_LIBRARY` is only the special-case of a pseudo library target that has *only* link dependencies, but is not a library by itself.

Next, the `INTERFACE_LINK_LIBRARIES` target property can contain a bunch of [generator expressions](https://cmake.org/cmake/help/v3.0/manual/cmake-generator-expressions.7.html) that need to be resolved. For shared library targets catkin can get away with ignoring transitive link dependencies because they are also stored in the ELF header of each so file and do not need to be listed explicitly in the linker command line. But for static libraries the incomplete resolution leads to linker errors due to missing symbols if transitive link dependencies are simply ignored.

Example from `OpenCVModules.cmake` and `OpenCVModules-release.cmake`:
```cmake
# Create imported target tegra_hal
add_library(tegra_hal STATIC IMPORTED)

# Create imported target libprotobuf
add_library(libprotobuf STATIC IMPORTED)

# Create imported target opencv_core
add_library(opencv_core STATIC IMPORTED)

set_target_properties(opencv_core PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:dl>;\$<LINK_ONLY:m>;\$<LINK_ONLY:log>;\$<LINK_ONLY:tegra_hal>;/opt/android/sdk/android-ndk-r18b/platforms/android-24/arch-arm64/usr/lib/libz.so;\$<LINK_ONLY:libcpufeatures>;\$<LINK_ONLY:tegra_hal>"
)

# Import target "tegra_hal" for configuration "Release"
set_property(TARGET tegra_hal APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(tegra_hal PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/share/OpenCV-3.3.1-dev/3rdparty/lib/libtegra_hal.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS tegra_hal )
list(APPEND _IMPORT_CHECK_FILES_FOR_tegra_hal "${_IMPORT_PREFIX}/share/OpenCV-3.3.1-dev/3rdparty/lib/libtegra_hal.a" )

# Import target "libprotobuf" for configuration "Release"
set_property(TARGET libprotobuf APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libprotobuf PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/share/OpenCV-3.3.1-dev/3rdparty/lib/liblibprotobuf.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS libprotobuf )
list(APPEND _IMPORT_CHECK_FILES_FOR_libprotobuf "${_IMPORT_PREFIX}/share/OpenCV-3.3.1-dev/3rdparty/lib/liblibprotobuf.a" )

# Import target "opencv_core" for configuration "Release"
set_property(TARGET opencv_core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_core PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libopencv_core3.a"
  )
```

Without this patch, `libtegra_hal.a` and other `LINK_ONLY` archives would not be added to the exported libraries list in the generated `image_geometryConfig.cmake`:
```cmake
set(libraries "image_geometry;/opt/ros_android/target/lib/libopencv_stitching3.a;/opt/ros_android/target/lib/libopencv_superres3.a;/opt/ros_android/target/lib/libopencv_videostab3.a;/opt/ros_android/target/lib/libopencv_aruco3.a;/opt/ros_android/target/lib/libopencv_bgsegm3.a;/opt/ros_android/target/lib/libopencv_bioinspired3.a;/opt/ros_android/target/lib/libopencv_ccalib3.a;/opt/ros_android/target/lib/libopencv_dpm3.a;/opt/ros_android/target/lib/libopencv_face3.a;/opt/ros_android/target/lib/libopencv_photo3.a;/opt/ros_android/target/lib/libopencv_fuzzy3.a;/opt/ros_android/target/lib/libopencv_img_hash3.a;/opt/ros_android/target/lib/libopencv_line_descriptor3.a;/opt/ros_android/target/lib/libopencv_optflow3.a;/opt/ros_android/target/lib/libopencv_reg3.a;/opt/ros_android/target/lib/libopencv_rgbd3.a;/opt/ros_android/target/lib/libopencv_saliency3.a;/opt/ros_android/target/lib/libopencv_stereo3.a;/opt/ros_android/target/lib/libopencv_structured_light3.a;/opt/ros_android/target/lib/libopencv_phase_unwrapping3.a;/opt/ros_android/target/lib/libopencv_surface_matching3.a;/opt/ros_android/target/lib/libopencv_tracking3.a;/opt/ros_android/target/lib/libopencv_plot3.a;/opt/ros_android/target/lib/libopencv_datasets3.a;/opt/ros_android/target/lib/libopencv_text3.a;/opt/ros_android/target/lib/libopencv_dnn3.a;/opt/ros_android/target/share/OpenCV-3.3.1-dev/3rdparty/lib/liblibprotobuf.a;/opt/ros_android/target/lib/libopencv_xfeatures2d3.a;/opt/ros_android/target/lib/libopencv_ml3.a;/opt/ros_android/target/lib/libopencv_shape3.a;/opt/ros_android/target/lib/libopencv_video3.a;/opt/ros_android/target/lib/libopencv_ximgproc3.a;/opt/ros_android/target/lib/libopencv_calib3d3.a;/opt/ros_android/target/lib/libopencv_features2d3.a;/opt/ros_android/target/lib/libopencv_flann3.a;/opt/ros_android/target/lib/libopencv_highgui3.a;/opt/ros_android/target/lib/libopencv_videoio3.a;/opt/ros_android/target/lib/libopencv_xobjdetect3.a;/opt/ros_android/target/lib/libopencv_objdetect3.a;/opt/ros_android/target/lib/libopencv_imgcodecs3.a;/opt/ros_android/target/share/OpenCV-3.3.1-dev/3rdparty/lib/liblibjpeg.a;/opt/ros_android/target/share/OpenCV-3.3.1-dev/3rdparty/lib/liblibwebp.a;/opt/ros_android/target/share/OpenCV-3.3.1-dev/3rdparty/lib/liblibpng.a;/opt/ros_android/target/share/OpenCV-3.3.1-dev/3rdparty/lib/liblibtiff.a;/opt/ros_android/target/share/OpenCV-3.3.1-dev/3rdparty/lib/liblibjasper.a;/opt/ros_android/target/share/OpenCV-3.3.1-dev/3rdparty/lib/libIlmImf.a;/opt/ros_android/target/lib/libopencv_xphoto3.a;/opt/ros_android/target/lib/libopencv_imgproc3.a;/opt/ros_android/target/lib/libopencv_core3.a;/opt/android/sdk/android-ndk-r18b/platforms/android-24/arch-arm64/usr/lib/libz.so;/opt/ros_android/target/share/OpenCV-3.3.1-dev/3rdparty/lib/libcpufeatures.a;dl;m;log;/opt/ros_android/target/share/OpenCV-3.3.1-dev/3rdparty/lib/libtegra_hal.a")
```

Ideally, catkin would create proper CMake configuration files using the [export()](https://cmake.org/cmake/help/v3.0/command/export.html) and [install(EXPORT ...)](https://cmake.org/cmake/help/v3.0/command/install.html) mechanisms in [modern CMake](https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/) to export generated or imported targets including all their interface properties like [INTERFACE_LINK_LIBRARIES](https://cmake.org/cmake/help/v3.0/prop_tgt/INTERFACE_LINK_LIBRARIES.html), [INTERFACE_INCLUDE_DIRECTORIES](https://cmake.org/cmake/help/v3.0/prop_tgt/INTERFACE_INCLUDE_DIRECTORIES.html), [INTERFACE_COMPILE_DEFINITIONS](https://cmake.org/cmake/help/v3.0/prop_tgt/INTERFACE_COMPILE_DEFINITIONS.html) and even [INTERFACE_COMPILE_FEATURES](https://cmake.org/cmake/help/v3.5/prop_tgt/INTERFACE_COMPILE_FEATURES.html) and rely on built-in mechanism instead of trying to be smart, but that is probably not going to happen soon.

### CODE REVIEW

**Comment by meyerj** [comment]
In some cases the cmake configuration of packages that depend on OpenCV takes considerably longer (up to a minute or more) and cmake consumes 100% CPU. Not sure whether this can be simply fixed, e.g. by using [list_append_deduplicate()](https://github.com/ros/catkin/blob/kinetic-devel/cmake/list_append_deduplicate.cmake) instead of `list(APPEND result ...)`. The problem is that libraries can be listed multiple times with different flags `(debug|optimized|general)`, and removing and appending it again would change the result.

**Comment by jubeira** [comment]
Alright, so just for my own clarification:
- I understand that if the `DEPENDS` line in `catkin_package` macro is properly set (as in [here](https://github.com/Intermodalics/ros_android/pull/27/files)), for `catkin` packages we shouldn't have link errors even without this patch.
- We still have problems with packages such as `OpenCV` and packages that build on top of them such as `image_geometry`. This patch would allow `catkin` to solve transitive dependencies in a more generic way preventing linking errors. 
  - Does this mean we could remove [OpenCV's patch](https://github.com/Intermodalics/ros_android/pull/24) by using the fix in this PR?
  - Do we have another package that benefits from this PR besides `OpenCV` and packages that build on top of it? In other words, are we patching `catkin` only to prevent patching `OpenCV`?
- About performance, I wouldn't worry too much about it at this stage if this solution is generic enough.

**Comment by meyerj** [comment]
> Alright, so just for my own clarification:
> 
> * I understand that if the `DEPENDS` line in `catkin_package` macro is properly set (as in [here](https://github.com/Intermodalics/ros_android/pull/27/files)), for `catkin` packages we shouldn't have link errors even without this patch.

It depends (literally). With `catkin_package(DEPENDS Foo)`, if `Foo_LIBRARIES` only lists actual library file names or names of imported targets without any transitive dependencies, there is no difference. But if there are transitive dependencies, like in case of `OpenCV` (3rd-party libraries and `libtegra_hal.a`), it does not work for static libraries. In this case even dependencies not used in the public headers, but only in the source code of a library (e.g. `opencv_imgcodecs`) need to be added to the linker command line. For shared libraries there is no problem because the references to internal libraries are stored in the header of the dynamic section and transitive link dependencies do not have to be listed explicitly.

> * We still have problems with packages such as `OpenCV` and packages that build on top of them such as `image_geometry`. This patch would allow `catkin` to solve transitive dependencies in a more generic way preventing linking errors.
>   * Does this mean we could remove [OpenCV's patch](https://github.com/Intermodalics/ros_android/pull/24) by using the fix in this PR?

Yes, could be. At least the `cv_bridge.patch` part. Still, I think that the solution provided by this patch is cleaner. I think the linker errors I got without this patch were in packages that only depend on `image_geometry` but not on `cv_bridge`. Without this patch the internal OpenCV libraries are missing from the list of exported libraries in the generated `image_geometryConfig.cmake`.

>   * Do we have another package that benefits from this PR besides `OpenCV` and packages that build on top of it? In other words, are we patching `catkin` only to prevent patching `OpenCV`?

At the moment I am only aware of `OpenCVModules.cmake` that exports targets with `INTERFACE_LINK_LIBRARIES` set. So yes, for the set of packages currently being compiled it would be an options to patch the respective packages that do export `OpenCV` as a dependency:

```
$ grep -E 'DEPENDS.*OpenCV' catkin_ws/src/ -R
catkin_ws/src/image_transport_plugins/compressed_image_transport/CMakeLists.txt:  DEPENDS OpenCV
catkin_ws/src/image_transport_plugins/compressed_depth_image_transport/CMakeLists.txt:  DEPENDS OpenCV
catkin_ws/src/vision_opencv/cv_bridge/CMakeLists.txt.rej:-  DEPENDS OpenCV
catkin_ws/src/vision_opencv/image_geometry/CMakeLists.txt:               DEPENDS OpenCV
catkin_ws/src/image_pipeline/image_rotate/CMakeLists.txt:  DEPENDS OpenCV
catkin_ws/src/image_pipeline/depth_image_proc/CMakeLists.txt:    DEPENDS ${MY_EIGEN} Boost OpenCV
catkin_ws/src/image_pipeline/image_proc/CMakeLists.txt:  DEPENDS OpenCV
```

But we also added another library dependency which does so in a private fork.

And actually [FindBoost.cmake](https://github.com/Kitware/CMake/blob/v3.6.3/Modules/FindBoost.cmake#L72:L76) exports targets with `INTERFACE_LINK_LIBRARIES`, e.g. also link to `Threads::Threads` when linking to `Boost_THREAD_LIBRARIES`:
```cmake
# Implicit dependencies such as Boost::filesystem requiring
# Boost::system will be automatically detected and satisfied, even
# if system is not specified when using find_package and if
# Boost::system is not added to target_link_libraries.  If using
# Boost::thread, then Thread::Thread will also be added automatically.

# ...
        if(_Boost_${UPPERCOMPONENT}_DEPENDENCIES)
          unset(_Boost_${UPPERCOMPONENT}_TARGET_DEPENDENCIES)
          foreach(dep ${_Boost_${UPPERCOMPONENT}_DEPENDENCIES})
            list(APPEND _Boost_${UPPERCOMPONENT}_TARGET_DEPENDENCIES Boost::${dep})
          endforeach()
          if(COMPONENT STREQUAL "thread")
            list(APPEND _Boost_${UPPERCOMPONENT}_TARGET_DEPENDENCIES Threads::Threads)
          endif()
          set_target_properties(Boost::${COMPONENT} PROPERTIES
            INTERFACE_LINK_LIBRARIES "${_Boost_${UPPERCOMPONENT}_TARGET_DEPENDENCIES}")
        endif()
```


> * About performance, I wouldn't worry too much about it at this stage if this solution is generic enough.

I plan to submit this patch to upstream https://github.com/ros/catkin and ask for comments (what we should do for some of the other patches, too).

**Comment by jubeira** [comment]
I see, thanks for the answers!
Let's get this PR merged then. In my experience a patch like this will probably take a while to get merged in `catkin`, but anyway it's worth the try, and getting comments could be useful as well.

**Comment by jubeira** [comment]
I just ran a complete build with the current head and this patch on top of it and it worked. I did notice some packages taking a while (~3 mins) at its `cmake` stage, but they are mostly top-level patches, so at all times other packages are being compiled simultaneously. In that sense, it doesn't block the overall compilation process very badly :+1:

**Comment by jubeira** [comment]
Solved conflicts, merging now.

**Pull request merged**
