### PR TITLE
cv_bridge: replace imported library targets by the full path to OpenCV_LIBRARIES

### PR DESCRIPTION
**Pull request by meyerj**
catkin does replace exported libraries that are imported targets (like `opencv_core`, `opencv_imgproc` and `opencv_imgcodecs`) by the full paths to these libraries in [catkin_libraries.cmake:258](https://github.com/ros/catkin/blob/4812667954e4cb7f99a753ffd4d725047e73a73b/cmake/catkin_package.cmake#L258), with subsequent deduplication.

If we add the OpenCV imported targets directly in `cv_bridge-extras.cmake.in`, deduplication does not work and derived packages end up with both, the full path and the target in `<pkg>_LIBRARIES` and `catkin_LIBRARIES`. There is no immediate problem with that, apart from the fact that it is not nice.

But in one case this caused a linker error in a non-catkin package that depends indirectly on `cv_bridge` and OpenCV, where the link directory was not set and the linker was failing due to not finding `-lopencv_core`, `-lopencv_imgproc` and `-lopencv_imgcodecs`.

### CODE REVIEW

**Comment by meyerj** [comment]
Actually simply removing that patch might also work. I do not see a reason why not.

The `cv_bridge-extras.cmake.in` script was patched in #24 to fix linker errors due to missing transitive dependencies of OpenCV libraries, but later we patched catkin in #51 to handle the problem at its core. With that patch I think the original, unpatched `cv_bridge` package should work as-is.

**Review by jubeira — APPROVED** [review]
LGTM! I'd also agree with removing the patch if it already works with the patched `catkin`.

**Comment by meyerj** [comment]
> Actually simply removing that patch might also work. I do not see a reason why not.

I tested this yesterday and it seems to work. I will update the pull request soon.

**Comment by meyerj** [comment]
Replaced by https://github.com/Intermodalics/ros_android/pull/113.

**Pull request closed without merging**
