### PR TITLE
opencv: patch 3rdparty/libtiff/CMakeLists.txt to fix unknown CMake command error

### PR DESCRIPTION
**Pull request by meyerj**
Not sure why this was only triggered after a fresh rebuild:
```
CMake Error at /opt/ros_android/catkin_ws /src/opencv3/3rdparty/libtiff/CMakeLists.txt:67 (check_type_size):
  Unknown CMake command "check_type_size".
```

### CODE REVIEW

**Comment by jubeira** [comment]
`cv_bridge` is not finding `OpenCV` when I test this:
```
Errors     << cv_bridge:cmake /opt/ros_android/output/catkin_ws/logs/cv_bridge/build.cmake.000.log                                                                                                         
CMake Error at /opt/ros_android/output/catkin_ws/src/vision_opencv/cv_bridge/CMakeLists.txt:16 (find_package):
  Could not find a package configuration file provided by "OpenCV" (requested
  version 3) with any of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake
```
I'll investigate a bit more; the error seems to be unrelated to this.

**Comment by jubeira** [comment]
I don't have issues with the current `kinetic` branch, but when I merge this branch with `kinetic` locally packages that depend on `OpenCV` can't find it. Any ideas?

**Comment by meyerj** [comment]
> I'll investigate a bit more; the error seems to be unrelated to this.

Indeed. Maybe delete `catkin_ws/build/opencv3` and try again?

**Comment by jubeira** [comment]
I had the error in a fresh build; I'll run one more test to confirm this just in case.

**Comment by jubeira** [comment]
I tried this patch with a clean docker container as well but I'm still getting the error.
I saw the `CMakeError` pointed out when doing a _second_ build without this patch (not when starting clean), so I think this fix makes sense, but I can't get the workspace to build properly on the first shot with this patch.

Meanwhile, the CMake error goes away if you delete the `OpenCV3` folder under the `build` directory. I'll try to figure out _why_ catkin isn't finding packages on top of OpenCV with this.

**Comment by jubeira** [comment]
@meyerj sorry for hijacking the branch; @ivanpauno pointed me to the right direction with this issue that was giving me quite some trouble: `do_everything` was exporting `CMAKE_PREFIX_PATH` incorrectly. I'm not sure why this patch triggered the error, but with https://github.com/Intermodalics/ros_android/pull/66/commits/bf6c729dbf63a2d827febfc1e8ef4dc84bb8c118 I can compile everything with your patch properly.

I'll just merge it as the new changes are pretty small.

**Comment by meyerj** [comment]
> @meyerj sorry for hijacking the branch; @ivanpauno pointed me to the right direction with this issue that was giving me quite some trouble: `do_everything` was exporting `CMAKE_PREFIX_PATH` incorrectly. I'm not sure why this patch triggered the error, but with [bf6c729](https://github.com/Intermodalics/ros_android/commit/bf6c729dbf63a2d827febfc1e8ef4dc84bb8c118) I can compile everything with your patch properly.

Well, it's not "wrong", but there are many ways to achieve the same goal and indeed it might be not necessary anymore with catkin_tools. Did you verify that it is also not necessary for any of the non-catkin libs that use cmake? For example, `CMAKE_PREFIX_PATH` is checked [here](https://github.com/Intermodalics/ros_android/blob/kinetic/utils.sh#L42) and indirectly forwarded as `CMAKE_INSTALL_PREFIX` to cmake. Some scripts treat it as a synonym for `$target`, which is only valid as long as all packages can find their dependencies in and are installed to the same directory and not really a clean solution.

catkin_tools (or the `catkin` command line tool) takes control of `CMAKE_PREFIX_PATH` and passes it as a command-line argument to cmake depending on the `catkin config --extend EXTEND_PATH` argument or the underlays cached from the environment at first invocation.

But the most important thing is that when cross-compiling and [CMAKE_FIND_ROOT_PATH](https://cmake.org/cmake/help/v3.0/variable/CMAKE_FIND_ROOT_PATH.html) is in effect, with the settings in [android.toolchain.cmake](https://android.googlesource.com/platform/ndk/+/7e81426ab3323198663806ccfdb242349d099a15/build/cmake/android.toolchain.cmake#278) packages, libraries and include files are only searched in paths below each entry in `CMAKE_FIND_ROOT_PATH` - which is good to not accidentally find and use libraries installed on the host. Search directories in `CMAKE_PREFIX_PATH` are applied as *additional* path suffixes. So basically `CMAKE_FIND_ROOT_PATH` takes over the role of `CMAKE_PREFIX_PATH`, and the latter might be set or not because nothing can be found in `/path/to/target/path/to/target` anyway. It only works because [find_package](https://cmake.org/cmake/help/v3.0/command/find_package.html#command:find_package) and friends also search in default locations like `/share` or `/lib/cmake` below each entry of `CMAKE_FIND_ROOT_PATH`.

Also note that CMake automatically adds [CMAKE_INSTALL_PREFIX](https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html) to [CMAKE_SYSTEM_PREFIX_PATH](https://cmake.org/cmake/help/v3.0/variable/CMAKE_SYSTEM_PREFIX_PATH.html) which is searched by default, but after all entries in [CMAKE_PREFIX_PATH](https://cmake.org/cmake/help/v3.0/variable/CMAKE_PREFIX_PATH.html). So unless the order is important to support package overlaying, the install-prefix of the current workspace does not need to be added to `CMAKE_PREFIX_PATH` explicitly.

**Comment by ivanpauno** [comment]
I think not using CMAKE_PREFIX_PATH is a good idea, and only let catkin_tools using it.
But is still some places where it was expected:

- build_cpp.sh:
         Boost related flags are using it.
- build_library_with_toolchain.sh: 
         Many flags are set using it.
- copy_boost.sh:
        Is taking where the target dir is located from here.
- utils.sh:
        The instructions using to build a cmake library are here, and it is using CMAKE_PREFIX_PATH to set many cmake 
        variables.

In all the cases CMAKE_PREFIX_PATH is not needed as an environment variable (we should test that building a library with cmake_build() in utils continuous working fine) . We should use variable, like TARGET or something like that.

**Comment by jubeira** [comment]
Thanks for the comments; I'll double check and send a follow-up PR if necessary.

**Comment by jubeira** [comment]
Today I had the same problem as yesterday: `cv_bridge` was not finding `OpenCV`.
After digging a while, I just figured that the `opencv` patch is broken: the line introduced here https://github.com/Intermodalics/ros_android/pull/66/commits/f0e47e00a036c04eb892bebb8d91c8b8d632028a is making the last two chunks fail silently. Then, the `OpenCVConfig` file wasn't being properly installed, and that's why it failed (this wasn't related with `CMAKE_PREFIX_PATH`; as you both point out it was probably not being used before as the `ROOT_PATH/CMAKE_PREFIX_PATH` was something invalid.

**Pull request merged**
