### PR TITLE
Patched octomap library. Don't compile octovis.

### PR DESCRIPTION
**Pull request by ivanpauno**
Fix octomap library

### CODE REVIEW

**Review by jubeira — APPROVED** [review]
Thanks @ivanpauno, LGTM!

**Comment by meyerj** [comment]
Kinetic comes with octomap 1.8.1 and it is also listed as such in [ndk.rosinstall](https://github.com/Intermodalics/ros_android/blob/kinetic/ndk.rosinstall#L421:L424). Not sure why it has been installed as a standalone library before, without catkin, but I would expect that the same patch also applies to the kinetic version.

**Comment by jubeira** [comment]
Let's try using the one packed with ROS (switching to `isolated` build if necessary); for now let's put this one on hold.

**Comment by jubeira** [comment]
This is being superseded by #30

**Pull request closed without merging**
