### PR TITLE
Minimal reorganization

### PR DESCRIPTION
**Pull request by ivanpauno**
- Deleted files folder, including some files related with the old app build process.
- Moved pluginlib_helper from files to scripts.
- Stop downloading rospkg, it's already installed inside the docker container.
- Moved toolchain file inside a "cmake" folder.
- Updated scripts with this changes.

### CODE REVIEW

**Review by jubeira — COMMENTED** [review]
Codewise looks good; I haven't tested it yet.
I have a doubt about this point:

> Stop downloading rospkg, it's already installed inside the docker container.

`rospkg` is also downloaded within the catkin workspace, but I don't see how it's accessible to pluginlib helper at the time the script is called. Am I missing something?

**Comment by ivanpauno** [comment]
> Codewise looks good; I haven't tested it yet.
> I have a doubt about this point:
> 
> > Stop downloading rospkg, it's already installed inside the docker container.
> 
> `rospkg` is also downloaded within the catkin workspace, but I don't see how it's accessible to pluginlib helper at the time the script is called. Am I missing something?

rospkg was downloaded directly inside "files" folder before, and was added as a system library download (not in the catkin_ws) in the last reorganization, and copied to "files" folder from there.

It was used only in "plugin_collect.py", specifying from which folder import. It's not really needed, as is part of the packages downloaded with ros-core (in /usr/lib/python2.7/dist-packages/rospkg)

**Review by jubeira — APPROVED** [review]
Tested, LGTM!
@meyerj PTAL if you have some time; this cleans up the repo a bit which is always welcome IMO.

**Review by meyerj — APPROVED** [review]
Not tested, but @jubeira did and the diff LGTM. Thanks!

**Pull request merged**
