### PR TITLE
Build example workspace in its own private install-space

### LINKED ISSUE #108: Build example workspace (or any other) in its own private install-space
I did not like the fact that the `example_workspace`, when building with `--samples`, installs to the same install prefix as the system libs and core ROS packages. In my opinion this install-space should stay free of example code and could also be copied between containers and systems to save some time, e.g. when working in a team.

The same applies to any other workspace that could be built with `build_catkin_workspace.sh`. The script is universal enough to be used by users directly, if it would source the `config.sh` script on its own.

I have a version that adds an `--extend` argument to [build_catkin_workspace.sh](https://github.com/Intermodalics/ros_android/blob/kinetic/scripts/build_catkin_workspace.sh) and changes the default install prefix to `workspace/install`, which would be the default with catkin. There is no problem with that approach, but the `CMAKE_FIND_ROOT_PATH` must list all underlay workspaces.

I don't have time right now to cleanup the patch and submit a PR. I will do so next week. Just wanted to hear your opinion first, @jubeira and @ivanpauno.

### PR DESCRIPTION
**Pull request by meyerj**
As suggested in #108. I did not update the README yet.
Is this more or less what you meant in https://github.com/Intermodalics/ros_android/issues/108#issuecomment-459320328, @ivanpauno ?

### CODE REVIEW

**Review by ivanpauno — APPROVED** [review]
LGTM
Line 247 of install.sh is probably not more necessary after using --extend option
https://github.com/Intermodalics/ros_android/blob/747557602798d14dd9a5288acb2be3a2f719abc1/install.sh#L247-L252

**Comment by meyerj** [comment]
> LGTM
> Line 247 of install.sh is probably not more necessary after using --extend option

Thanks, I think you are right. Removed in https://github.com/Intermodalics/ros_android/pull/110/commits/2854ec92a644b5d097bc40169c3ba2697155442f.

**Review by jubeira — APPROVED** [review]
Looks great!
I'll send a PR with updated instructions for `build_catkin_workspace` usage and how to build code on top of the main workspace in general.

**Comment by jubeira** [comment]
@meyerj I think we can merge this one, and in any case retarget #111 to `kinetic`.

**Pull request merged**
