### PR TITLE
Upgrade bfl and orocos_kdl to kinetic versions and build in catkin_ws

### PR DESCRIPTION
**Pull request by meyerj**
same versions as released in Kinetic:
- http://repositories.ros.org/status_page/ros_kinetic_default.html?q=bfl
- http://repositories.ros.org/status_page/ros_kinetic_default.html?q=orocos_kdl

### CODE REVIEW

**Review by jubeira — APPROVED** [review]
LGTM!

**Comment by meyerj** [comment]
Nope, we should use the versions in `ndk.rosinstall` instead and remove these packages here. I think the issue is that with `catkin_make` non-catkin packages could not be built as part of the catkin workspace and had to be separated. But with `catkin_make_isolated` or `catkin_tools` this is not a problem.

**Comment by jubeira** [comment]
Sounds good; let's make that a rule: if a library is released as a ROS package, let's use that version and build it inside the catkin workspace. As you say, now that we are using `catkin_tools` it should be more straightforward. 
/cc @ivanpauno 

I'm testing the changes now; I'll come back once it finishes building.

**Review by jubeira — APPROVED** [review]
I just finished testing; it works without issues.

**Pull request merged**
